server:
    port: 8080

spring:
    profiles:
        active: dev
        
    devtools:
        restart:
            enabled: true
        livereload:
            enabled: false # we use gulp + BrowserSync for livereload

    h2:
      console:
        enabled: true
        path: /h2-console

    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:h2:mem:moit;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        #url: jdbc:mysql://localhost:3306/example?useUnicode=true&characterEncoding=utf8&useSSL=false
        username: sa
        password: 
        hikari:
            minimum-idle: 5
            maximum-pool-size: 10
            data-source-properties:
                cachePrepStmts: true
                prepStmtCacheSize: 250
                prepStmtCacheSqlLimit: 2048
                useServerPrepStmts: true
                connectionTimeout: 30000
        
    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        database: H2
        show-sql: true
        properties:
            hibernate.id.new_generator_mappings: true
            hibernate.cache.use_second_level_cache: true
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: true
           
    data:
        elasticsearch:
            cluster-name: vault-elastic
            cluster-nodes: localhost:19300
            properties:
                path:
                  logs: target/elasticsearch/log
                  data: target/elasticsearch/data
                  